(web) README updates and fixes for Windows
- update the installation and deployment instructions for Windows, to
  include the PowerShell `set-executionpolicy` stuff which is required
  to activate the Python virtualenv

- use colorama library to make ANSI colors Just Work™ on Windows

- Jinja template paths are apparently "not necessarily filesystem
  paths"[1] so using `os.path.join` to create a path to a template where
  it exists inside a subdirectory (like `templates/data/README.txt`)
  causes problems on Windows, where os.path.sep is `\`

  - the fix is gross, but it's to replace backslashes with forward
    slashes to keep Jinja's FileSystemLoader happy -- which really
    *should* tolerate whatever the native path separator is in the
    first place, but alas

- explicitly set UTF-8 encoding when writing output files in
  lib.templates, so that you don't get an error like this in the process

    > UnicodeEncodeError: 'charmap' codec can't encode character
    > '\u2318' in position 10513: character maps to <undefined>

  This occurs because `locale.getencoding()` returns `cp12521` on
  Windows; ref. https://docs.python.org/3/library/functions.html#open.

- don't try to use `os.symlink` in the Invoke tasks file, because you
  get this error in that case

    > OSError: [WinError 1314] A required privilege is not held by the
    > client: '../theme/dot-htaccess' -> '.htaccess'

  Apparently, making a symbolic link is something only an administrator
  can do on Windows, because Bill only knows.